name: ItemCollections
main: ItemCollections.Main
version: 0.5
api-version: 1.15
commands:
    ic:
        description: Lists collection commands.
        usage: Command not recognized. Use /ic to see the list of commands.
        permission: ic.basic
        permission-message: You don't have permission to do this.
permissions:
    ic.*:
        description: Gives access to all commands.
        children:
            ic.basic: true
            ic.create: true
            ic.delete: true
            ic.edit: true
            ic.listcollections: true
            ic.listitems: true
            ic.collection: true
    ic.basic:
        description: Shows you the ic commands you can use.
        default: true
    ic.create:
        description: Allows you to create collections.
        default: op
    ic.delete:
        description: Allows you to delete collections.
        default: op
    ic.edit:
        description: Allows you to modify collections.
        default: op
    ic.listcollections:
        description: Allows you to see a list of collections.
        default: true
    ic.listitems:
        description: Allows you to list the items in a collection.
        default: true
    ic.collection:
        description: Allows you to turn in a collection.
        default: true 